allowBuilds:
  '@prisma/engines': false
  '@tailwindcss/oxide': false
  esbuild: false
  prisma: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - sharp
  - unrs-resolver
